import React, { useEffect, useRef } from "react";
import { useGLTF, useProgress } from "@react-three/drei";

export function Bonk(props) {
  const { nodes, materials } = useGLTF("/bonk.glb");
  const { active, progress, errors, item, loaded, total } = useProgress();
  useEffect(() => {
    console.log(progress);

  }, [progress]);
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_1.geometry}
          material={materials["Opaque(229,234,237)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_2.geometry}
          material={materials["Opaque(198,193,188)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_3.geometry}
          material={materials["Opaque(255,242,232)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_4.geometry}
          material={materials["Opaque(221,232,255)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_5.geometry}
          material={materials["Opaque(128,128,128)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_6.geometry}
          material={materials["Opaque(255,255,255)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_7.geometry}
          material={materials.Prism_Opaque}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_8.geometry}
          material={materials["Opaque(26,26,26)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_9.geometry}
          material={materials["Opaque(166,158,150)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_10.geometry}
          material={materials["Opaque(165,158,150)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_11.geometry}
          material={materials["Opaque(64,64,64)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_12.geometry}
          material={materials["Opaque(203,210,239)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_13.geometry}
          material={materials.Prism_Opaque_1}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_14.geometry}
          material={materials["Opaque(202,209,238)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_15.geometry}
          material={materials["Opaque(165,132,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_16.geometry}
          material={materials["Opaque(135,140,140)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_17.geometry}
          material={materials["Opaque(29,29,29)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_18.geometry}
          material={materials["Opaque(244,244,244)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_19.geometry}
          material={materials["Opaque(63,63,63)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_20.geometry}
          material={materials["Opaque(178,178,178)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_21.geometry}
          material={materials["Opaque(25,25,25)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_22.geometry}
          material={materials["Aluminum_-_Polished"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_23.geometry}
          material={materials["Steel_-_Satin"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_24.geometry}
          material={materials["Aluminum_-_Satin"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_25.geometry}
          material={materials["Plastic_-_Glossy_(Grey)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_26.geometry}
          material={materials["Powder_Coat_-_Rough_(Blue)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_27.geometry}
          material={materials["Opaque(255,0,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_28.geometry}
          material={materials["Opaque(192,192,192)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_29.geometry}
          material={materials["Opaque(217,225,221)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_30.geometry}
          material={materials["Opaque(128,128,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_31.geometry}
          material={materials["Opaque(192,0,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_32.geometry}
          material={materials["Acrylic_(Red)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_33.geometry}
          material={materials["Plastic_-_Matte_(Red)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_34.geometry}
          material={materials["Polycarbonate_(Bronze)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_35.geometry}
          material={materials["Opaque(228,233,237)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_36.geometry}
          material={materials["Opaque(170,178,196)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_37.geometry}
          material={materials["Opaque(137,89,86)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_38.geometry}
          material={materials["Opaque(214,114,99)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_39.geometry}
          material={materials["Opaque(0,128,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_40.geometry}
          material={materials["Opaque(0,192,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_41.geometry}
          material={materials["Paint_-_Enamel_Glossy_(Green)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_42.geometry}
          material={materials["Opaque(190,188,186)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_43.geometry}
          material={materials["Steel_-_Rough"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_44.geometry}
          material={materials["Aluminum_-_Bead_Blasted"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_45.geometry}
          material={materials["Opaque(49,52,52)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_46.geometry}
          material={materials["Aluminum_-_Satin_1"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_47.geometry}
          material={materials["Polycarbonate_(Clear)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_48.geometry}
          material={materials["Opaque(204,206,204)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_49.geometry}
          material={materials["Opaque(177,25,25)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_50.geometry}
          material={materials["Opaque(33,138,33)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_51.geometry}
          material={materials["Opaque(221,221,13)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_52.geometry}
          material={materials["Opaque(5,5,5)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_53.geometry}
          material={materials["Opaque(245,245,245)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_54.geometry}
          material={materials["Opaque(254,213,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_55.geometry}
          material={materials["Opaque(177,177,177)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_56.geometry}
          material={materials["Opaque(10,10,10)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_57.geometry}
          material={materials["Opaque(72,71,61)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_58.geometry}
          material={materials["Opaque(0,100,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_59.geometry}
          material={materials["Opaque(231,214,172)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_60.geometry}
          material={materials["Opaque(178,0,0)"]}
        />
        <mesh
          geometry={nodes.Bonk_Top_Level_Robot_Assembly_v163_61.geometry}
          material={materials["Paint_-_Enamel_Glossy_(White)"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bonk.glb");
